apiVersion: v2
name: open-webui
version: 6.22.0
appVersion: 0.6.15
home: https://www.openwebui.com/
icon: >-
  https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
description: 'Open WebUI: A User-Friendly Web Interface for Chat Interactions 👋'
keywords:
  - llm
  - chat
  - web-ui
  - open-webui
sources:
  - https://github.com/open-webui/helm-charts
  - https://github.com/open-webui/open-webui/pkgs/container/open-webui
  - https://github.com/otwld/ollama-helm/
  - https://hub.docker.com/r/ollama/ollama
  - https://charts.bitnami.com/bitnami
annotations:
  licenses: MIT
dependencies:
  - name: ollama
    repository: https://github.com/Kazu-Hitachi/ollama
    version: '>=0.24.0'
    import-values:
      - child: service
        parent: ollama.service
    condition: ollama.enabled
  - name: pipelines
    repository: https://github.com/Kazu-Hitachi/TestArgoCD/pipelines-0.7.0/pipelines
    version: '>=0.0.1'
    import-values:
      - child: service
        parent: pipelines.service
    condition: pipelines.enabled
  - name: tika
    repository: https://github.com/Kazu-Hitachi/TestArgoCD/tika-2.9.0/tika
    version: '>=2.9.0'
    condition: tika.enabled
  - name: redis
    repository: https://github.com/Kazu-Hitachi/TestArgoCD/redis-21.2.7/redis
    version: '>=20.6.2'
    alias: redis-cluster
    condition: redis-cluster.enabled
  - name: postgresql
    repository: https://github.com/Kazu-Hitachi/TestArgoCD/postgresql-16.7.15/postgresql
    version: '>=15.5.38'
    alias: postgresql
    condition: postgresql.enabled
